'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization

Namespace Adeptive.ResWare.Services
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteData", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")>  _
    Partial Public Class ReceiveNoteData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CoordinatorTypeIDField As System.Nullable(Of Integer)
        
        Private CurativeIDField As Integer
        
        Private CurativeTypeField As Adeptive.ResWare.Services.ReceiveCurativeTypeEnum
        
        Private DocumentsField() As Adeptive.ResWare.Services.ReceiveNoteDocument
        
        Private FileNumberField As String
        
        Private NoteBodyField As String
        
        Private NoteSubjectField As String
        
        Private ToCoordinatorIDField As Integer
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CoordinatorTypeID() As System.Nullable(Of Integer)
            Get
                Return Me.CoordinatorTypeIDField
            End Get
            Set
                Me.CoordinatorTypeIDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurativeID() As Integer
            Get
                Return Me.CurativeIDField
            End Get
            Set
                Me.CurativeIDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurativeType() As Adeptive.ResWare.Services.ReceiveCurativeTypeEnum
            Get
                Return Me.CurativeTypeField
            End Get
            Set
                Me.CurativeTypeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Documents() As Adeptive.ResWare.Services.ReceiveNoteDocument()
            Get
                Return Me.DocumentsField
            End Get
            Set
                Me.DocumentsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property FileNumber() As String
            Get
                Return Me.FileNumberField
            End Get
            Set
                Me.FileNumberField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NoteBody() As String
            Get
                Return Me.NoteBodyField
            End Get
            Set
                Me.NoteBodyField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NoteSubject() As String
            Get
                Return Me.NoteSubjectField
            End Get
            Set
                Me.NoteSubjectField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToCoordinatorID() As Integer
            Get
                Return Me.ToCoordinatorIDField
            End Get
            Set
                Me.ToCoordinatorIDField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveCurativeTypeEnum", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")>  _
    Public Enum ReceiveCurativeTypeEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PRE_CLOSING = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        POLICY = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteDocument", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")>  _
    Partial Public Class ReceiveNoteDocument
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private DescriptionField As String
        
        Private DocumentBodyField() As Byte
        
        Private DocumentTypeIDField As Integer
        
        Private FileNameField As String
        
        Private InternalOnlyField As Boolean
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                Me.DescriptionField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property DocumentBody() As Byte()
            Get
                Return Me.DocumentBodyField
            End Get
            Set
                Me.DocumentBodyField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property DocumentTypeID() As Integer
            Get
                Return Me.DocumentTypeIDField
            End Get
            Set
                Me.DocumentTypeIDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                Me.FileNameField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InternalOnly() As Boolean
            Get
                Return Me.InternalOnlyField
            End Get
            Set
                Me.InternalOnlyField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")>  _
    Partial Public Class ReceiveNoteResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private MessageField As String
        
        Private ResponseCodeField As Adeptive.ResWare.Services.ReceiveNoteResponseCode
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                Me.MessageField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ResponseCode() As Adeptive.ResWare.Services.ReceiveNoteResponseCode
            Get
                Return Me.ResponseCodeField
            End Get
            Set
                Me.ResponseCodeField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteResponseCode", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")>  _
    Public Enum ReceiveNoteResponseCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SUCCESS = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        INVALID_LOGIN = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        INVALID_FILE_NUMBER = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DOWN_FOR_MAINTENANCE = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NOTE_ERROR = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DOCUMENT_ERROR = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SECURITY_ERROR = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNEXPECTED_ERROR = 10
    End Enum
End Namespace


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IReceiveNoteService")>  _
Public Interface IReceiveNoteService
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReceiveNoteService/ReceiveNote", ReplyAction:="http://tempuri.org/IReceiveNoteService/ReceiveNoteResponse")>  _
    Function ReceiveNote(ByVal NoteData As Adeptive.ResWare.Services.ReceiveNoteData) As Adeptive.ResWare.Services.ReceiveNoteResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReceiveNoteService/ReceiveNote", ReplyAction:="http://tempuri.org/IReceiveNoteService/ReceiveNoteResponse")>  _
    Function ReceiveNoteAsync(ByVal NoteData As Adeptive.ResWare.Services.ReceiveNoteData) As System.Threading.Tasks.Task(Of Adeptive.ResWare.Services.ReceiveNoteResponse)
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface IReceiveNoteServiceChannel
    Inherits IReceiveNoteService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class ReceiveNoteServiceClient
    Inherits System.ServiceModel.ClientBase(Of IReceiveNoteService)
    Implements IReceiveNoteService
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Function ReceiveNote(ByVal NoteData As Adeptive.ResWare.Services.ReceiveNoteData) As Adeptive.ResWare.Services.ReceiveNoteResponse Implements IReceiveNoteService.ReceiveNote
        Return MyBase.Channel.ReceiveNote(NoteData)
    End Function
    
    Public Function ReceiveNoteAsync(ByVal NoteData As Adeptive.ResWare.Services.ReceiveNoteData) As System.Threading.Tasks.Task(Of Adeptive.ResWare.Services.ReceiveNoteResponse) Implements IReceiveNoteService.ReceiveNoteAsync
        Return MyBase.Channel.ReceiveNoteAsync(NoteData)
    End Function
End Class
