'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SilkReceiveNoteService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteData", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ReceiveNoteData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CoordinatorTypeIDField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurativeIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurativeTypeField As SilkReceiveNoteService.ReceiveCurativeTypeEnum
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentsField() As SilkReceiveNoteService.ReceiveNoteDocument
        
        Private FileNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoteBodyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoteSubjectField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToCoordinatorIDField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CoordinatorTypeID() As System.Nullable(Of Integer)
            Get
                Return Me.CoordinatorTypeIDField
            End Get
            Set
                If (Me.CoordinatorTypeIDField.Equals(value) <> true) Then
                    Me.CoordinatorTypeIDField = value
                    Me.RaisePropertyChanged("CoordinatorTypeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurativeID() As Integer
            Get
                Return Me.CurativeIDField
            End Get
            Set
                If (Me.CurativeIDField.Equals(value) <> true) Then
                    Me.CurativeIDField = value
                    Me.RaisePropertyChanged("CurativeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurativeType() As SilkReceiveNoteService.ReceiveCurativeTypeEnum
            Get
                Return Me.CurativeTypeField
            End Get
            Set
                If (Me.CurativeTypeField.Equals(value) <> true) Then
                    Me.CurativeTypeField = value
                    Me.RaisePropertyChanged("CurativeType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Documents() As SilkReceiveNoteService.ReceiveNoteDocument()
            Get
                Return Me.DocumentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentsField, value) <> true) Then
                    Me.DocumentsField = value
                    Me.RaisePropertyChanged("Documents")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property FileNumber() As String
            Get
                Return Me.FileNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNumberField, value) <> true) Then
                    Me.FileNumberField = value
                    Me.RaisePropertyChanged("FileNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NoteBody() As String
            Get
                Return Me.NoteBodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoteBodyField, value) <> true) Then
                    Me.NoteBodyField = value
                    Me.RaisePropertyChanged("NoteBody")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NoteSubject() As String
            Get
                Return Me.NoteSubjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoteSubjectField, value) <> true) Then
                    Me.NoteSubjectField = value
                    Me.RaisePropertyChanged("NoteSubject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToCoordinatorID() As Integer
            Get
                Return Me.ToCoordinatorIDField
            End Get
            Set
                If (Me.ToCoordinatorIDField.Equals(value) <> true) Then
                    Me.ToCoordinatorIDField = value
                    Me.RaisePropertyChanged("ToCoordinatorID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveCurativeTypeEnum", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")>  _
    Public Enum ReceiveCurativeTypeEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PRE_CLOSING = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        POLICY = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteDocument", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ReceiveNoteDocument
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        Private DocumentBodyField() As Byte
        
        Private DocumentTypeIDField As Integer
        
        Private FileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InternalOnlyField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property DocumentBody() As Byte()
            Get
                Return Me.DocumentBodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentBodyField, value) <> true) Then
                    Me.DocumentBodyField = value
                    Me.RaisePropertyChanged("DocumentBody")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property DocumentTypeID() As Integer
            Get
                Return Me.DocumentTypeIDField
            End Get
            Set
                If (Me.DocumentTypeIDField.Equals(value) <> true) Then
                    Me.DocumentTypeIDField = value
                    Me.RaisePropertyChanged("DocumentTypeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InternalOnly() As Boolean
            Get
                Return Me.InternalOnlyField
            End Get
            Set
                If (Me.InternalOnlyField.Equals(value) <> true) Then
                    Me.InternalOnlyField = value
                    Me.RaisePropertyChanged("InternalOnly")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ReceiveNoteResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private MessageField As String
        
        Private ResponseCodeField As SilkReceiveNoteService.ReceiveNoteResponseCode
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ResponseCode() As SilkReceiveNoteService.ReceiveNoteResponseCode
            Get
                Return Me.ResponseCodeField
            End Get
            Set
                If (Me.ResponseCodeField.Equals(value) <> true) Then
                    Me.ResponseCodeField = value
                    Me.RaisePropertyChanged("ResponseCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReceiveNoteResponseCode", [Namespace]:="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")>  _
    Public Enum ReceiveNoteResponseCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SUCCESS = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        INVALID_LOGIN = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        INVALID_FILE_NUMBER = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DOWN_FOR_MAINTENANCE = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NOTE_ERROR = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DOCUMENT_ERROR = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SECURITY_ERROR = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNEXPECTED_ERROR = 10
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SilkReceiveNoteService.IReceiveNoteService")>  _
    Public Interface IReceiveNoteService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReceiveNoteService/ReceiveNote", ReplyAction:="http://tempuri.org/IReceiveNoteService/ReceiveNoteResponse")>  _
        Function ReceiveNote(ByVal NoteData As SilkReceiveNoteService.ReceiveNoteData) As SilkReceiveNoteService.ReceiveNoteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReceiveNoteService/ReceiveNote", ReplyAction:="http://tempuri.org/IReceiveNoteService/ReceiveNoteResponse")>  _
        Function ReceiveNoteAsync(ByVal NoteData As SilkReceiveNoteService.ReceiveNoteData) As System.Threading.Tasks.Task(Of SilkReceiveNoteService.ReceiveNoteResponse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IReceiveNoteServiceChannel
        Inherits SilkReceiveNoteService.IReceiveNoteService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ReceiveNoteServiceClient
        Inherits System.ServiceModel.ClientBase(Of SilkReceiveNoteService.IReceiveNoteService)
        Implements SilkReceiveNoteService.IReceiveNoteService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ReceiveNote(ByVal NoteData As SilkReceiveNoteService.ReceiveNoteData) As SilkReceiveNoteService.ReceiveNoteResponse Implements SilkReceiveNoteService.IReceiveNoteService.ReceiveNote
            Return MyBase.Channel.ReceiveNote(NoteData)
        End Function
        
        Public Function ReceiveNoteAsync(ByVal NoteData As SilkReceiveNoteService.ReceiveNoteData) As System.Threading.Tasks.Task(Of SilkReceiveNoteService.ReceiveNoteResponse) Implements SilkReceiveNoteService.IReceiveNoteService.ReceiveNoteAsync
            Return MyBase.Channel.ReceiveNoteAsync(NoteData)
        End Function
    End Class
End Namespace
