'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace VLRArcServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="VLRArcServiceReference.IOrderPlacement")>  _
    Public Interface IOrderPlacement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderPlacement/PlaceRequest", ReplyAction:="http://tempuri.org/IOrderPlacement/PlaceRequestResponse")>  _
        Function PlaceRequest(ByVal pRequestXml As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderPlacement/PlaceRequest", ReplyAction:="http://tempuri.org/IOrderPlacement/PlaceRequestResponse")>  _
        Function PlaceRequestAsync(ByVal pRequestXml As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOrderPlacementChannel
        Inherits VLRArcServiceReference.IOrderPlacement, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OrderPlacementClient
        Inherits System.ServiceModel.ClientBase(Of VLRArcServiceReference.IOrderPlacement)
        Implements VLRArcServiceReference.IOrderPlacement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function PlaceRequest(ByVal pRequestXml As String) As String Implements VLRArcServiceReference.IOrderPlacement.PlaceRequest
            Return MyBase.Channel.PlaceRequest(pRequestXml)
        End Function
        
        Public Function PlaceRequestAsync(ByVal pRequestXml As String) As System.Threading.Tasks.Task(Of String) Implements VLRArcServiceReference.IOrderPlacement.PlaceRequestAsync
            Return MyBase.Channel.PlaceRequestAsync(pRequestXml)
        End Function
    End Class
End Namespace
